version: "3"
networks:
  default:
    name: eil

services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: eil
    ports:
      - 5432:5432
    volumes:
      - ./init-eil-database.sh:/docker-entrypoint-initdb.d/init-database.sh

  postgres-sso:
    image: postgres:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: keycloak_db
    volumes:
      - ./keycloak-db.sql:/docker-entrypoint-initdb.d/keycloak-db.sql
    ports:
      - 5435:5432

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: example
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_URL_HOST: postgres-sso
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command:
      - start-dev
    depends_on:
      - postgres-sso

  cpg-server:
    image: etenlab/cpg-server:latest
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: example
      DB_NAME: eil
      RUN_MIGRATIONS: "false"
      MODE: DEV
      PORT: 80
    ports:
      - 8201:80
    depends_on:
      - postgres
